function cfg = step10b_pilot_config()
% STEP10B_PILOT_CONFIG Safe local config for C01/C06 MATLAB pilot.
% Generated by scripts/10b_prepare_matlab_pilot_generation.py.
% dry_run is true by default; change to false only after dry-run validation.

cfg = struct();
cfg.repo_root = 'C:/Users/E713181/Documents/Dados/FILIPA_DADOS';
cfg.filipa_root = 'C:/Users/E713181/Documents/Dados/FILIPA_DADOS/data/dadosParaPedro_Fresnel/dadosParaPedro_Fresnel';
cfg.filipa_code_root = fullfile(cfg.filipa_root, '00.Code');
cfg.thetao_nc = 'C:/Users/E713181/Documents/Dados/FILIPA_DADOS/data/dadosParaPedro_Fresnel/dadosParaPedro_Fresnel/01.Data/ALL/thetao_20260427.nc';
cfg.dss_exe = 'C:/Users/E713181/Documents/Dados/FILIPA_DADOS/data/dadosParaPedro_Fresnel/dadosParaPedro_Fresnel/input_all/DSS.C.64.exe';
cfg.bathy_reference_hres = 'C:/Users/E713181/Documents/Dados/FILIPA_DADOS/data/dadosParaPedro_Fresnel/dadosParaPedro_Fresnel/01.Data/October/HRes/CMEMSnaza_20241030_HResNew.nc';
cfg.output_base = 'C:/Users/E713181/Documents/Dados/FILIPA_DADOS/results/fossum_roi_x490_step10b_matlab_pilot_generation_20260516_140623';
cfg.cmems_grid_output_dir = fullfile(cfg.output_base, 'cmems_grid');
cfg.hres_output_dir = fullfile(cfg.output_base, 'hres');
cfg.sim_output_root = fullfile(cfg.output_base, 'simulations', 'HighRes');
cfg.logs_dir = fullfile(cfg.output_base, 'matlab_logs');

cfg.pilot_dates = {'2024-07-03', '2024-07-04', '2023-12-22', '2023-12-17'};
cfg.pilot_classes = {'C01_frontal', 'C01_frontal', 'C06_mixed', 'C06_mixed'};
cfg.pilot_class_ids = [1 1 6 6];
cfg.pilot_day_indices_370 = [250 251 56 51];

cfg.dry_run = true;
cfg.input_days = 14;
cfg.output_days = 2;
cfg.hres_interpolation_factor = 10;
cfg.depth_indices = 1:17;
cfg.nbr_sim = 100;
cfg.operation_ll_corner = [39.50955, -9.43575];
cfg.operation_ur_corner = [39.75365, -9.03419];
cfg.variogram = [1000,400,100; 1000,400,100; 1000,400,100; 1000,400,100; 1000,350,100; ...
    1000,300,100; 800,300,100; 800,300,90; 550,300,90; 500,200,90; 450,200,80; ...
    450,180,80; 400,150,80; 400,150,70; 350,120,70; 400,150,60; 400,150,60];
end
