"""Export clean prototype assets for computer vision.

This script rebuilds prototypes directly from numeric source arrays and
membership CSV files generated by the final working pipeline. It does not
crop previously rendered figures.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]

SEED_DIR_RX = re.compile(r"^seed(\d+)$")
K_DIR_RX = re.compile(r"^k(\d+)$")
GLOBAL_DISTANCE_RX = re.compile(r"^class_(\d+)_distance_to_prototype\.csv$")
LOCAL_DISTANCE_RX = re.compile(r"^subclass_(\d+)_distance_to_prototype\.csv$")


@dataclass(frozen=True)
class SeedRun:
    seed: int
    seed_dir: Path
    global_dir: Path
    local_dir: Path


def log(msg: str) -> None:
    print(f"[cv-prototype-export] {msg}")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Export clean CV-ready prototype PNG/NPY/mask assets from final working pipeline outputs."
    )
    p.add_argument(
        "--pipeline-root",
        type=Path,
        default=None,
        help=(
            "Pipeline run root containing seedXX/global and seedXX/local_class02. "
            "If omitted, auto-discovery is used."
        ),
    )
    p.add_argument(
        "--out-root",
        type=Path,
        default=None,
        help="Output root for exports. Default: <pipeline-root>/computer_vision_exports",
    )
    p.add_argument(
        "--seeds",
        type=int,
        nargs="*",
        default=None,
        help="Optional list of seeds to export (e.g. --seeds 11). Default: all discovered seeds.",
    )
    p.add_argument(
        "--cmap",
        type=str,
        default="coolwarm",
        help="Colormap used for clean PNG rendering.",
    )
    p.add_argument(
        "--vlim-percentile",
        type=float,
        default=98.0,
        help="Percentile of |X_norm| used to set fixed symmetric vmin/vmax.",
    )
    p.add_argument(
        "--mask-render",
        choices=["transparent", "neutral"],
        default="transparent",
        help="How invalid/masked pixels are rendered in PNG exports.",
    )
    p.add_argument(
        "--neutral-gray",
        type=float,
        default=0.5,
        help="Gray level in [0,1] used when --mask-render=neutral.",
    )
    p.add_argument(
        "--png-width",
        type=int,
        default=None,
        help="Optional output PNG width in pixels (use together with --png-height).",
    )
    p.add_argument(
        "--png-height",
        type=int,
        default=None,
        help="Optional output PNG height in pixels (use together with --png-width).",
    )
    p.add_argument(
        "--png-dpi",
        type=int,
        default=150,
        help="DPI used when rendering fixed-size PNGs.",
    )
    return p.parse_args()


def _first_existing_file(candidates: Sequence[Path]) -> Path | None:
    for p in candidates:
        if p.exists() and p.is_file():
            return p
    return None


def resolve_numeric_input_paths() -> Dict[str, Path]:
    paths = {
        "X_norm": _first_existing_file(
            [
                ROOT / "results" / "fossum" / "X_surface_300_norm.npy",
                ROOT / "results" / "plots" / "X_surface_300_norm.npy",
            ]
        ),
        "mask": _first_existing_file(
            [
                ROOT / "results" / "fossum" / "mask_common.npy",
                ROOT / "results" / "plots" / "mask_common.npy",
            ]
        ),
    }
    missing = [k for k, v in paths.items() if v is None]
    if missing:
        raise FileNotFoundError(
            "Missing required numeric inputs: "
            + ", ".join(missing)
            + " (checked under results/fossum and results/plots)."
        )
    return {k: v for k, v in paths.items() if v is not None}


def load_numeric_inputs(paths: Dict[str, Path], vlim_percentile: float) -> Tuple[np.ndarray, np.ndarray, Tuple[float, float]]:
    X_norm = np.load(paths["X_norm"]).astype(np.float32, copy=False)
    mask = np.load(paths["mask"]).astype(bool, copy=False)

    if X_norm.ndim != 3:
        raise RuntimeError(f"Expected X_norm as 3D array, got shape={X_norm.shape}")
    if mask.shape != X_norm.shape[1:]:
        raise RuntimeError(f"Mask shape mismatch: mask={mask.shape}, grid={X_norm.shape[1:]}")

    X_norm = X_norm.copy()
    X_norm[:, ~mask] = np.nan

    valid_vals = X_norm[:, mask]
    vlim = float(np.percentile(np.abs(valid_vals), float(vlim_percentile)))
    if not np.isfinite(vlim) or vlim <= 0.0:
        vlim = 1.0
    return X_norm, mask, (-vlim, +vlim)


def class_mean_image(class_stack: np.ndarray, mask: np.ndarray) -> np.ndarray:
    mean_img = np.mean(np.nan_to_num(class_stack, nan=0.0), axis=0).astype(np.float32, copy=False)
    mean_img[~mask] = np.nan
    return mean_img


def build_png_cmap(cmap_name: str, mask_render: str, neutral_gray: float):
    cmap = plt.get_cmap(cmap_name).copy()
    if mask_render == "transparent":
        cmap.set_bad(color=(0.0, 0.0, 0.0, 0.0))
    else:
        g = float(np.clip(neutral_gray, 0.0, 1.0))
        cmap.set_bad(color=(g, g, g, 1.0))
    return cmap


def save_clean_png(
    out_png: Path,
    field_2d: np.ndarray,
    mask: np.ndarray,
    cmap,
    vmin: float,
    vmax: float,
    png_width: int | None,
    png_height: int | None,
    png_dpi: int,
) -> None:
    masked = np.ma.array(
        field_2d.astype(np.float32, copy=False),
        mask=(~mask) | (~np.isfinite(field_2d)),
        copy=False,
    )
    out_png.parent.mkdir(parents=True, exist_ok=True)
    if png_width is not None and png_height is not None:
        fig = plt.figure(
            figsize=(float(png_width) / float(png_dpi), float(png_height) / float(png_dpi)),
            dpi=float(png_dpi),
            frameon=False,
        )
        fig.patch.set_alpha(0.0)
        ax = fig.add_axes([0.0, 0.0, 1.0, 1.0])
        ax.set_axis_off()
        ax.imshow(
            masked,
            origin="lower",
            cmap=cmap,
            vmin=float(vmin),
            vmax=float(vmax),
            aspect="auto",
            interpolation="nearest",
        )
        fig.savefig(out_png, dpi=float(png_dpi), transparent=True, bbox_inches=None, pad_inches=0.0)
        plt.close(fig)
    else:
        plt.imsave(out_png, masked, cmap=cmap, vmin=float(vmin), vmax=float(vmax), origin="lower")


def read_member_indices(csv_path: Path, candidate_cols: Sequence[str]) -> np.ndarray:
    df = pd.read_csv(csv_path)
    col = None
    for c in candidate_cols:
        if c in df.columns:
            col = c
            break
    if col is None:
        raise RuntimeError(f"Could not find any of {candidate_cols} in {csv_path}")

    idx = df[col].astype(int).to_numpy()
    if idx.size == 0:
        raise RuntimeError(f"No members found in {csv_path}")
    if np.unique(idx).size != idx.size:
        raise RuntimeError(f"Duplicate member indices in {csv_path}")
    return np.sort(idx.astype(np.int32, copy=False))


def export_single_prototype(
    out_dir: Path,
    base_name: str,
    prototype: np.ndarray,
    mask: np.ndarray,
    cmap,
    vmin: float,
    vmax: float,
    png_width: int | None,
    png_height: int | None,
    png_dpi: int,
) -> Dict[str, object]:
    out_dir.mkdir(parents=True, exist_ok=True)
    png_path = out_dir / f"{base_name}_clean.png"
    npy_path = out_dir / f"{base_name}.npy"
    mask_path = out_dir / f"{base_name}_mask.npy"

    np.save(npy_path, prototype.astype(np.float32, copy=False))
    np.save(mask_path, mask.astype(bool, copy=False))
    save_clean_png(
        out_png=png_path,
        field_2d=prototype,
        mask=mask,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
        png_width=png_width,
        png_height=png_height,
        png_dpi=png_dpi,
    )

    return {
        "base_name": base_name,
        "png_path": str(png_path.resolve()),
        "array_path": str(npy_path.resolve()),
        "mask_path": str(mask_path.resolve()),
        "array_shape": [int(v) for v in prototype.shape],
        "mask_shape": [int(v) for v in mask.shape],
    }


def discover_pipeline_root(explicit: Path | None) -> Path:
    if explicit is not None:
        root = explicit.resolve()
        if not root.exists() or not root.is_dir():
            raise FileNotFoundError(f"pipeline root does not exist: {root}")
        return root

    candidate_roots: List[Path] = []
    base_a = ROOT / "results" / "final_working_pipeline"
    base_b = ROOT / "results" / "fossum" / "final_working_pipeline"
    for base in [base_a, base_b]:
        if not base.exists() or not base.is_dir():
            continue
        for child in sorted(base.iterdir()):
            if not child.is_dir():
                continue
            has_manifest = (child / "pipeline_manifest.json").exists()
            has_seed = any(p.is_dir() and SEED_DIR_RX.match(p.name) for p in child.iterdir())
            if has_manifest and has_seed:
                candidate_roots.append(child.resolve())

    if not candidate_roots:
        raise FileNotFoundError(
            "Could not auto-discover pipeline root under "
            "results/final_working_pipeline/ or results/fossum/final_working_pipeline/."
        )

    def score(path: Path) -> Tuple[int, int, float]:
        parent_is_primary = int(path.parent.resolve() == (ROOT / "results" / "final_working_pipeline").resolve())
        official_tag = int("official_fixed_dictionary" in path.name.lower())
        return (parent_is_primary, official_tag, path.stat().st_mtime)

    candidate_roots.sort(key=score, reverse=True)
    return candidate_roots[0]


def collect_seed_runs(pipeline_root: Path) -> List[SeedRun]:
    out: List[SeedRun] = []
    for p in sorted(pipeline_root.iterdir()):
        if not p.is_dir():
            continue
        m = SEED_DIR_RX.match(p.name)
        if not m:
            continue
        seed = int(m.group(1))
        global_dir = p / "global"
        local_dir = p / "local_class02"
        if global_dir.exists() and local_dir.exists():
            out.append(SeedRun(seed=seed, seed_dir=p.resolve(), global_dir=global_dir.resolve(), local_dir=local_dir.resolve()))
    out.sort(key=lambda r: r.seed)
    if not out:
        raise RuntimeError(f"No seed directories with global/local_class02 found under {pipeline_root}")
    return out


def filter_seed_runs(seed_runs: List[SeedRun], requested_seeds: Sequence[int] | None) -> List[SeedRun]:
    if not requested_seeds:
        return seed_runs
    wanted = {int(s) for s in requested_seeds}
    filtered = [sr for sr in seed_runs if int(sr.seed) in wanted]
    missing = sorted(wanted.difference({int(sr.seed) for sr in filtered}))
    if missing:
        raise RuntimeError(f"Requested seeds not found under pipeline root: {missing}")
    filtered.sort(key=lambda r: r.seed)
    return filtered


def parse_global_distance_files(global_dir: Path) -> List[Tuple[int, Path]]:
    parsed: List[Tuple[int, Path]] = []
    for f in sorted(global_dir.glob("class_*_distance_to_prototype.csv")):
        m = GLOBAL_DISTANCE_RX.match(f.name)
        if m:
            parsed.append((int(m.group(1)), f.resolve()))
    parsed.sort(key=lambda t: t[0])
    return parsed


def parse_local_distance_files(local_k_dir: Path) -> List[Tuple[int, Path]]:
    parsed: List[Tuple[int, Path]] = []
    for f in sorted(local_k_dir.glob("subclass_*_distance_to_prototype.csv")):
        m = LOCAL_DISTANCE_RX.match(f.name)
        if m:
            parsed.append((int(m.group(1)), f.resolve()))
    parsed.sort(key=lambda t: t[0])
    return parsed


def main() -> None:
    args = parse_args()
    if (args.png_width is None) != (args.png_height is None):
        raise ValueError("Use --png-width and --png-height together (or omit both).")
    if args.png_width is not None and int(args.png_width) <= 0:
        raise ValueError("--png-width must be > 0")
    if args.png_height is not None and int(args.png_height) <= 0:
        raise ValueError("--png-height must be > 0")
    if int(args.png_dpi) <= 0:
        raise ValueError("--png-dpi must be > 0")

    pipeline_root = discover_pipeline_root(args.pipeline_root)
    seed_runs = collect_seed_runs(pipeline_root)
    seed_runs = filter_seed_runs(seed_runs=seed_runs, requested_seeds=args.seeds)
    out_root = (args.out_root.resolve() if args.out_root is not None else (pipeline_root / "computer_vision_exports").resolve())

    input_paths = resolve_numeric_input_paths()
    X_norm, mask, (vmin, vmax) = load_numeric_inputs(paths=input_paths, vlim_percentile=float(args.vlim_percentile))
    cmap = build_png_cmap(cmap_name=str(args.cmap), mask_render=str(args.mask_render), neutral_gray=float(args.neutral_gray))

    log(f"pipeline_root={pipeline_root}")
    log(f"out_root={out_root}")
    log(f"seeds={','.join(str(s.seed) for s in seed_runs)}")
    log(f"loaded X_norm={input_paths['X_norm']} mask={input_paths['mask']} shape={X_norm.shape}")
    log(
        "fixed visualization range: "
        f"vmin={vmin:.6f}, vmax={vmax:.6f}, cmap={args.cmap}, mask_render={args.mask_render}, "
        f"png_size={args.png_width}x{args.png_height}"
    )

    export_records: List[Dict[str, object]] = []

    for sr in seed_runs:
        log(f"processing seed{sr.seed:02d}")
        seed_out = out_root / f"seed{sr.seed:02d}"

        global_files = parse_global_distance_files(sr.global_dir)
        if not global_files:
            raise RuntimeError(f"No global class distance files found in {sr.global_dir}")
        for class_id, csv_path in global_files:
            idx = read_member_indices(csv_path, candidate_cols=["image_idx_0_based"])
            proto = class_mean_image(X_norm[idx], mask=mask)
            rec = export_single_prototype(
                out_dir=seed_out / "global",
                base_name=f"prototype_class_{class_id:02d}",
                prototype=proto,
                mask=mask,
                cmap=cmap,
                vmin=vmin,
                vmax=vmax,
                png_width=args.png_width,
                png_height=args.png_height,
                png_dpi=int(args.png_dpi),
            )
            rec.update(
                {
                    "seed": sr.seed,
                    "scope": "global",
                    "class_id": int(class_id),
                    "source_distance_csv": str(csv_path),
                    "n_members": int(idx.size),
                }
            )
            export_records.append(rec)

        local_k_dirs = [p for p in sorted(sr.local_dir.iterdir()) if p.is_dir() and K_DIR_RX.match(p.name)]
        for k_dir in local_k_dirs:
            k = int(K_DIR_RX.match(k_dir.name).group(1))  # type: ignore[union-attr]
            local_files = parse_local_distance_files(k_dir)
            for subclass_id, csv_path in local_files:
                idx = read_member_indices(csv_path, candidate_cols=["global_image_idx_0_based", "image_idx_0_based"])
                proto = class_mean_image(X_norm[idx], mask=mask)
                rec = export_single_prototype(
                    out_dir=seed_out / "local_class02" / k_dir.name,
                    base_name=f"subclass_prototype_{subclass_id:02d}",
                    prototype=proto,
                    mask=mask,
                    cmap=cmap,
                    vmin=vmin,
                    vmax=vmax,
                    png_width=args.png_width,
                    png_height=args.png_height,
                    png_dpi=int(args.png_dpi),
                )
                rec.update(
                    {
                        "seed": sr.seed,
                        "scope": "local_class02",
                        "k": int(k),
                        "subclass_id": int(subclass_id),
                        "source_distance_csv": str(csv_path),
                        "n_members": int(idx.size),
                    }
                )
                export_records.append(rec)

    validation_rows: List[Dict[str, object]] = []
    global_count = 0
    local_count = 0
    for rec in export_records:
        png_p = Path(str(rec["png_path"]))
        arr_p = Path(str(rec["array_path"]))
        mask_p = Path(str(rec["mask_path"]))
        arr = np.load(arr_p)
        msk = np.load(mask_p)

        ok_files = png_p.exists() and arr_p.exists() and mask_p.exists()
        ok_shape = tuple(arr.shape) == tuple(msk.shape)
        if not ok_shape:
            raise RuntimeError(f"Shape mismatch for exported pair: {arr_p} vs {mask_p}")

        validation_rows.append(
            {
                "base_name": rec["base_name"],
                "seed": int(rec["seed"]),
                "scope": str(rec["scope"]),
                "png_exists": bool(png_p.exists()),
                "array_exists": bool(arr_p.exists()),
                "mask_exists": bool(mask_p.exists()),
                "all_three_exist": bool(ok_files),
                "shape_match": bool(ok_shape),
                "array_shape": [int(v) for v in arr.shape],
                "mask_shape": [int(v) for v in msk.shape],
            }
        )

        if rec["scope"] == "global":
            global_count += 1
        elif rec["scope"] == "local_class02":
            local_count += 1

    manifest = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_pipeline_root": str(pipeline_root.resolve()),
        "source_scripts": [
            str((ROOT / "scripts" / "04a_separation_distance_probe_fossum_faithful_initial.py").resolve()),
            str((ROOT / "scripts" / "06_class02_local_refinement_sd30.py").resolve()),
        ],
        "source_numeric_inputs": {
            "X_norm": str(input_paths["X_norm"].resolve()),
            "mask_common": str(input_paths["mask"].resolve()),
        },
        "mask_convention": {
            "true": "ocean/valid",
            "false": "land/invalid",
            "dtype": "bool",
        },
        "array_domain": "normalized SST (X_surface_300_norm)",
        "visualization": {
            "vmin": float(vmin),
            "vmax": float(vmax),
            "vlim_percentile_abs": float(args.vlim_percentile),
            "colormap": str(args.cmap),
            "mask_render": str(args.mask_render),
            "origin": "lower",
            "autoscaling_per_image": False,
            "png_width": (None if args.png_width is None else int(args.png_width)),
            "png_height": (None if args.png_height is None else int(args.png_height)),
            "png_dpi": int(args.png_dpi),
        },
        "output_root": str(out_root),
        "output_structure": "computer_vision_exports/seedXX/{global|local_class02/kY}/",
        "notes": [
            "Prototypes rebuilt numerically from source arrays and full-membership distance CSV files.",
            "No manual crop or reuse of pre-rendered prototype PNGs was used.",
        ],
        "counts": {
            "seeds_processed": int(len(seed_runs)),
            "global_prototypes_exported": int(global_count),
            "local_class02_prototypes_exported": int(local_count),
            "total_exports": int(len(export_records)),
        },
        "exports": export_records,
        "validation": validation_rows,
    }

    out_root.mkdir(parents=True, exist_ok=True)
    manifest_path = out_root / "manifest_cv_exports.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    log(f"global prototypes exported: {global_count}")
    log(f"local class_02 prototypes exported: {local_count}")
    log(f"manifest: {manifest_path}")


if __name__ == "__main__":
    main()
