"""Prepare safe MATLAB Step10B pilot generation kit.

This creates non-destructive MATLAB adaptations of Filipa's original scripts.
The generated MATLAB config defaults to dry_run=true. No TEMPpred/STD outputs
are invented and no heavy DSS simulation is run by this Python preparer.
"""

from __future__ import annotations

import csv
import hashlib
import json
import shutil
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = ROOT / "scripts" / "matlab_step10b_pilot"
RESULTS = ROOT / "results"
STEP10A_REVALIDATED = RESULTS / "fossum_roi_x490_step10a_revalidated_with_local_filipa_data_20260516_095603"
FILIPA_ROOT = ROOT / "data" / "dadosParaPedro_Fresnel" / "dadosParaPedro_Fresnel"
ORIG_WRITE = FILIPA_ROOT / "00.Code" / "write14days.m"
ORIG_RUN = FILIPA_ROOT / "00.Code" / "runSimulations.m"
THETAO_NC = FILIPA_ROOT / "01.Data" / "ALL" / "thetao_20260427.nc"
DSS_EXE = FILIPA_ROOT / "input_all" / "DSS.C.64.exe"
BATHY_REFERENCE_HRES = FILIPA_ROOT / "01.Data" / "October" / "HRes" / "CMEMSnaza_20241030_HResNew.nc"
PILOT_CSV = STEP10A_REVALIDATED / "step10b_pilot_selected_dates.csv"


def now_tag() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.replace("\r\n", "\n"), encoding="utf-8")


def write_json(path: Path, payload: dict[str, Any]) -> None:
    write_text(path, json.dumps(payload, indent=2, ensure_ascii=True))


def matlab_path(path: Path) -> str:
    return str(path.resolve()).replace("\\", "/")


def pilot_rows() -> list[dict[str, Any]]:
    df = pd.read_csv(PILOT_CSV)
    return df.to_dict(orient="records")


def target_to_pred_date(date_str: str) -> datetime:
    return datetime.strptime(date_str, "%Y-%m-%d") - timedelta(days=1)


def required_hres_dates(rows: list[dict[str, Any]]) -> list[datetime]:
    dates = set()
    for row in rows:
        target = datetime.strptime(str(row["date"]), "%Y-%m-%d")
        dates.add(target - timedelta(days=1))
        dates.add(target + timedelta(days=1))
    return sorted(dates)


def expected_outputs(rows: list[dict[str, Any]], output_dir: Path) -> list[dict[str, Any]]:
    out = []
    hres_dir = output_dir / "hres"
    sim_root = output_dir / "simulations" / "HighRes"
    for d in required_hres_dates(rows):
        out.append(
            {
                "kind": "hres_input",
                "date": d.strftime("%Y-%m-%d"),
                "class_id": "",
                "depth": "",
                "expected_path": str(hres_dir / f"CMEMSnaza_{d.strftime('%Y%m%d')}_HResNew.nc"),
                "exists_now": (hres_dir / f"CMEMSnaza_{d.strftime('%Y%m%d')}_HResNew.nc").exists(),
            }
        )
    for row in rows:
        target = datetime.strptime(str(row["date"]), "%Y-%m-%d")
        pred = target - timedelta(days=1)
        project = sim_root / f"Daily_dpt_{pred.strftime('%Y%m%d')}"
        for depth in range(1, 18):
            out.append(
                {
                    "kind": "predmodel",
                    "date": target.strftime("%Y-%m-%d"),
                    "class_id": int(row["class_id"]),
                    "depth": depth,
                    "expected_path": str(project / f"{target.strftime('%d-%m-%Y')}_predModel_{depth}.nc"),
                    "exists_now": (project / f"{target.strftime('%d-%m-%Y')}_predModel_{depth}.nc").exists(),
                }
            )
    return out


def config_m(output_dir: Path, rows: list[dict[str, Any]]) -> str:
    dates = ", ".join([f"'{r['date']}'" for r in rows])
    classes = ", ".join([f"'{r['class_label']}'" for r in rows])
    class_ids = " ".join([str(int(r["class_id"])) for r in rows])
    day_indices = " ".join([str(int(r["day_index_370"])) for r in rows])
    return f"""function cfg = step10b_pilot_config()
% STEP10B_PILOT_CONFIG Safe local config for C01/C06 MATLAB pilot.
% Generated by scripts/10b_prepare_matlab_pilot_generation.py.
% dry_run is true by default; change to false only after dry-run validation.

cfg = struct();
cfg.repo_root = '{matlab_path(ROOT)}';
cfg.filipa_root = '{matlab_path(FILIPA_ROOT)}';
cfg.filipa_code_root = fullfile(cfg.filipa_root, '00.Code');
cfg.thetao_nc = '{matlab_path(THETAO_NC)}';
cfg.dss_exe = '{matlab_path(DSS_EXE)}';
cfg.bathy_reference_hres = '{matlab_path(BATHY_REFERENCE_HRES)}';
cfg.output_base = '{matlab_path(output_dir)}';
cfg.cmems_grid_output_dir = fullfile(cfg.output_base, 'cmems_grid');
cfg.hres_output_dir = fullfile(cfg.output_base, 'hres');
cfg.sim_output_root = fullfile(cfg.output_base, 'simulations', 'HighRes');
cfg.logs_dir = fullfile(cfg.output_base, 'matlab_logs');

cfg.pilot_dates = {{{dates}}};
cfg.pilot_classes = {{{classes}}};
cfg.pilot_class_ids = [{class_ids}];
cfg.pilot_day_indices_370 = [{day_indices}];

cfg.dry_run = true;
cfg.input_days = 14;
cfg.output_days = 2;
cfg.hres_interpolation_factor = 10;
cfg.depth_indices = 1:17;
cfg.nbr_sim = 100;
cfg.operation_ll_corner = [39.50955, -9.43575];
cfg.operation_ur_corner = [39.75365, -9.03419];
cfg.variogram = [1000,400,100; 1000,400,100; 1000,400,100; 1000,400,100; 1000,350,100; ...
    1000,300,100; 800,300,100; 800,300,90; 550,300,90; 500,200,90; 450,200,80; ...
    450,180,80; 400,150,80; 400,150,70; 350,120,70; 400,150,60; 400,150,60];
end
"""


WRITE_HRES_M = r"""function hres_table = write_selected_days_hres_step10b_pilot(cfg)
% WRITE_SELECTED_DAYS_HRES_STEP10B_PILOT Build HRes input files for pilot dates.
% This is a non-destructive adaptation of Filipa's write14days.m. It keeps
% the original 14-day window, local crop, and interpolation logic, but uses
% cfg paths/dates and writes only into cfg.output_base.

if nargin < 1
    cfg = step10b_pilot_config();
end

ensure_dir(cfg.cmems_grid_output_dir);
ensure_dir(cfg.hres_output_dir);
ensure_dir(cfg.logs_dir);

required_dates = required_hres_end_dates(cfg);
rows = {};

for k = 1:numel(required_dates)
    end_date = required_dates(k);
    hres_name = ['CMEMSnaza_', datestr(end_date, 'yyyymmdd'), '_HResNew.nc'];
    hres_path = fullfile(cfg.hres_output_dir, hres_name);
    rows(end+1,:) = {datestr(end_date, 'yyyy-mm-dd'), hres_path, cfg.dry_run}; %#ok<AGROW>
    if cfg.dry_run
        fprintf('[DRY-RUN] Would create HRes window ending %s -> %s\n', datestr(end_date), hres_path);
    end
end

hres_table = cell2table(rows, 'VariableNames', {'hres_end_date','hres_path','dry_run'});
writetable(hres_table, fullfile(cfg.logs_dir, 'step10b_hres_generation_plan.csv'));

if cfg.dry_run
    return
end

assert(isfile(cfg.thetao_nc), 'Missing thetao file: %s', cfg.thetao_nc);
assert(isfile(cfg.bathy_reference_hres), 'Missing bathy reference HRes: %s', cfg.bathy_reference_hres);

TIMEALL = ncread(cfg.thetao_nc, 'time');
all_days = datetime(1970,1,1,0,0,0) + seconds(TIMEALL);
lat = ncread(cfg.thetao_nc, 'latitude');
lon = ncread(cfg.thetao_nc, 'longitude');
dept = ncread(cfg.thetao_nc, 'depth');
temp_all = ncread(cfg.thetao_nc, 'thetao');

ref_lat_hres = ncread(cfg.bathy_reference_hres, 'LAT');
ref_lon_hres = ncread(cfg.bathy_reference_hres, 'LON');
ref_bathy_hres = ncread(cfg.bathy_reference_hres, 'BATHY');

for k = 1:numel(required_dates)
    end_date = required_dates(k);
    idx_end = find(dateshift(all_days, 'start', 'day') == dateshift(end_date, 'start', 'day'), 1, 'first');
    if isempty(idx_end)
        error('Date %s not found in thetao_nc time axis.', datestr(end_date, 'yyyy-mm-dd'));
    end
    idx_start = idx_end - cfg.input_days + 1;
    if idx_start < 1
        error('Date %s does not have the required %d-day lookback window.', datestr(end_date, 'yyyy-mm-dd'), cfg.input_days);
    end

    TEMP = squeeze(temp_all(:,:,:,idx_start:idx_end));
    TIME = squeeze(TIMEALL(idx_start:idx_end));

    idxLatMax = find(min(abs(lat-cfg.operation_ur_corner(1))) == abs(lat-cfg.operation_ur_corner(1)), 1) + 4;
    idxLatMin = find(min(abs(lat-cfg.operation_ll_corner(1))) == abs(lat-cfg.operation_ll_corner(1)), 1) - 4;
    idxLonMax = find(min(abs(lon-cfg.operation_ur_corner(2))) == abs(lon-cfg.operation_ur_corner(2)), 1) + 4;
    idxLonMin = find(min(abs(lon-cfg.operation_ll_corner(2))) == abs(lon-cfg.operation_ll_corner(2)), 1) - 4;

    LAT = lat(idxLatMin:idxLatMax);
    LON = lon(idxLonMin:idxLonMax);
    TEMP = TEMP(idxLonMin:idxLonMax, idxLatMin:idxLatMax, :, :);

    inc = cfg.hres_interpolation_factor;
    clear TempHRes
    for dpt = 1:size(TEMP,3)
        for tm = 1:size(TEMP,4)
            [xTq, yTq] = meshgrid(1:size(TEMP,2), 1:size(TEMP,1));
            [xTqnew, yTqnew] = meshgrid(linspace(1, size(TEMP,2), size(TEMP,2)*inc), linspace(1, size(TEMP,1), size(TEMP,1)*inc));
            TempHRes(:,:,dpt,tm) = interp2(xTq, yTq, TEMP(:,:,dpt,tm), xTqnew, yTqnew); %#ok<AGROW>
        end
    end
    LatHRes = interp1((1:size(LAT,1))', LAT, linspace(1, size(LAT,1), size(LAT,1)*inc)');
    LonHRes = interp1((1:size(LON,1))', LON, linspace(1, size(LON,1), size(LON,1)*inc)');

    if numel(LatHRes) ~= numel(ref_lat_hres) || numel(LonHRes) ~= numel(ref_lon_hres)
        error('Computed HRes grid does not match bathy reference grid.');
    end

    out_nc = fullfile(cfg.hres_output_dir, ['CMEMSnaza_', datestr(end_date, 'yyyymmdd'), '_HResNew.nc']);
    if isfile(out_nc)
        delete(out_nc);
    end
    nccreate(out_nc, 'TEMP', 'Dimensions', {'LON',size(TempHRes,1),'LAT',size(TempHRes,2),'DEPT',size(TempHRes,3),'TIME',size(TempHRes,4)});
    nccreate(out_nc, 'LAT', 'Dimensions', {'lat',size(LatHRes,1)});
    nccreate(out_nc, 'LON', 'Dimensions', {'lon',size(LonHRes,1)});
    nccreate(out_nc, 'BATHY', 'Dimensions', {'LON',size(ref_bathy_hres,1),'LAT',size(ref_bathy_hres,2)});
    nccreate(out_nc, 'DEPT', 'Dimensions', {'depth',size(dept,1)});
    nccreate(out_nc, 'TIME', 'Dimensions', {'seconds since 1970-01-01',size(TIME,1)});
    ncwrite(out_nc, 'TEMP', TempHRes);
    ncwrite(out_nc, 'BATHY', ref_bathy_hres);
    ncwrite(out_nc, 'DEPT', dept);
    ncwrite(out_nc, 'LAT', LatHRes);
    ncwrite(out_nc, 'LON', LonHRes);
    ncwrite(out_nc, 'TIME', TIME);
    fprintf('Created %s\n', out_nc);
end
end

function dates = required_hres_end_dates(cfg)
dates = datetime.empty(0,1);
for i = 1:numel(cfg.pilot_dates)
    target = datetime(cfg.pilot_dates{i}, 'InputFormat', 'yyyy-MM-dd');
    dates(end+1,1) = target - days(1); %#ok<AGROW>
    dates(end+1,1) = target + days(1); %#ok<AGROW>
end
dates = unique(dates);
end

function ensure_dir(path_)
if ~exist(path_, 'dir')
    mkdir(path_);
end
end
"""


RUN_SIM_M = r"""function sim_table = run_selected_days_simulations_step10b_pilot(cfg)
% RUN_SELECTED_DAYS_SIMULATIONS_STEP10B_PILOT Run DSS pilot simulations.
% Non-destructive adaptation of Filipa's runSimulations.m. Dry-run is the
% default and only prints expected work. Set cfg.dry_run=false after checking
% paths and HRes inputs.

if nargin < 1
    cfg = step10b_pilot_config();
end

addpath(genpath(cfg.filipa_code_root));
ensure_dir(cfg.sim_output_root);
ensure_dir(cfg.logs_dir);

rows = {};
for day_idx = 1:numel(cfg.pilot_dates)
    targetDate = datetime(cfg.pilot_dates{day_idx}, 'InputFormat', 'yyyy-MM-dd');
    predDate = targetDate - days(1);
    projectPath = fullfile(cfg.sim_output_root, ['Daily_dpt_', datestr(predDate, 'yyyymmdd')]);
    hresFile = fullfile(cfg.hres_output_dir, ['CMEMSnaza_', datestr(predDate, 'yyyymmdd'), '_HResNew.nc']);
    expectedFirst = fullfile(projectPath, [datestr(targetDate, 'dd-mm-yyyy'), '_predModel_1.nc']);
    rows(end+1,:) = {datestr(targetDate,'yyyy-mm-dd'), datestr(predDate,'yyyy-mm-dd'), hresFile, expectedFirst, cfg.dry_run}; %#ok<AGROW>
    if cfg.dry_run
        fprintf('[DRY-RUN] Would simulate target %s using HRes %s\n', datestr(targetDate), hresFile);
    end
end

sim_table = cell2table(rows, 'VariableNames', {'target_date','pred_date','hres_file','expected_predmodel_1','dry_run'});
writetable(sim_table, fullfile(cfg.logs_dir, 'step10b_simulation_plan.csv'));
if cfg.dry_run
    return
end

assert(isfile(cfg.dss_exe), 'Missing DSS executable: %s', cfg.dss_exe);

for day_idx = 1:numel(cfg.pilot_dates)
    targetDate = datetime(cfg.pilot_dates{day_idx}, 'InputFormat', 'yyyy-MM-dd');
    predDate = targetDate - days(1);
    projectPath = fullfile(cfg.sim_output_root, ['Daily_dpt_', datestr(predDate, 'yyyymmdd')]);
    ensure_dir(projectPath);
    imagesPath = fullfile(projectPath, 'Images');
    ensure_dir(imagesPath);

    fileReal = fullfile(cfg.hres_output_dir, ['CMEMSnaza_', datestr(predDate, 'yyyymmdd'), '_HResNew.nc']);
    assert(isfile(fileReal), 'Missing HRes input: %s', fileReal);

    temp = ncread(fileReal, 'TEMP');
    lat = ncread(fileReal, 'LAT');
    lon = ncread(fileReal, 'LON');
    bath = ncread(fileReal, 'BATHY');
    depth = ncread(fileReal, 'DEPT');

    for dpt = cfg.depth_indices
        priorFolderName = ['Priori_Nazare_', datestr(targetDate, 'dd-mm-yyyy'), '_', num2str(dpt)];
        pUTM = projcrs(32629);
        variogram = cfg.variogram(dpt,:);
        LAT = lat;
        LON = lon;
        TEMP = squeeze(temp(:,:,dpt,:));
        BATH = bath;
        TEMP(TEMP == 0) = NaN;

        nx = size(TEMP,1);
        ny = size(TEMP,2);
        inputDays = cfg.input_days;
        outputDays = cfg.output_days;
        nz = inputDays + outputDays;
        ox = 1; oy = 1; oz = 1;
        dx = 1; dy = 1; dz = 1;
        rangeX = variogram(:,1);
        rangeY = variogram(:,2);
        rangeZ = variogram(:,3);

        outputPath = fullfile(projectPath, priorFolderName);
        inputPath = fullfile(outputPath, 'input_all');
        ensure_dir(outputPath);
        ensure_dir(inputPath);
        copyfile(cfg.dss_exe, fullfile(inputPath, 'DSS.C.64.exe'));

        hardata = ones(1,4);
        dept_counter = 1;
        for y = oy:ny
            for x = ox:nx
                for z = oz:inputDays
                    if ~isnan(TEMP(x,y,z))
                        hardata(dept_counter,:) = [x, y, z, TEMP(x,y,z)];
                        dept_counter = dept_counter + 1;
                    end
                end
            end
        end
        seconddata = [hardata(:,1)+10000, hardata(:,2)+10000, hardata(:,3), hardata(:,4)];

        mask = zeros(nx*ny*nz,4);
        mask_counter = 1;
        for z = oz:nz
            for y = oy:ny
                for x = ox:nx
                    if isnan(TEMP(x,y,1))
                        mask(mask_counter,:) = [x, y, z, -1];
                    else
                        mask(mask_counter,:) = [x, y, z, 0];
                    end
                    mask_counter = mask_counter + 1;
                end
            end
        end
        grid2gslib(mask(:,4), fullfile(inputPath, 'mask.out'));
        grid2gslib(BATH, fullfile(outputPath, 'Bath.gslib'));

        write_harddata(fullfile(inputPath, 'temp.gslib'), hardata);
        write_harddata(fullfile(inputPath, 'auxi.gslib'), seconddata);

        writealldata_naza([inputPath, filesep], 'alldata', [outputPath, filesep], dpt, TEMP, ox, oy, oz, nx, ny, inputDays, outputDays, pUTM, LAT, LON, predDate, cfg.hres_output_dir, dpt);

        nbrSim = cfg.nbr_sim;
        covTab = [200 200 200];
        krig_RANGE = [rangeX*2 rangeY*2 rangeZ*2];
        krig_ANG = [0 0 0; 0 0 0; 0 0 0];
        var_temp_ANG = [0 0 0; 0 0 0; 0 0 0];
        var_temp_RANGE = [rangeX rangeY rangeZ 0.9; rangeX rangeY rangeZ 0.9];
        varType = [1; 1; 1];
        varNugget = [0.1; 0.1; 0.1];
        zonesFileName = fullfile(inputPath, 'mask.out');
        bounds = repmat([min(hardata(:,4)) max(hardata(:,4))], 2, 1);

        parFileDSS('GEOEAS', 0, 0, 0, [inputPath, filesep], [[inputPath, filesep, 'temp.gslib']; [inputPath, filesep, 'auxi.gslib']], ...
            nbrSim, fullfile(outputPath, 'sim'), 0, 'no file', ['no file'; 'no file'], bounds, ...
            [nx, ox, dx], [ny, oy, dy], [nz, oz, dz], 'no file', 0, 'no file', krig_ANG, krig_RANGE, ...
            var_temp_ANG, var_temp_RANGE, varType, varNugget, zonesFileName, 2, 10, 0, 'no file', 0, ...
            'no file', 0, covTab);

        readoutput_AUV(0, nbrSim, nx, ny, nz, [inputPath, filesep], [outputPath, filesep], inputDays);
        copyfile(fullfile(inputPath, 'auxi.gslib'), fullfile(outputPath, 'auxi.gslib'));
        copyfile(fullfile(inputPath, 'temp.gslib'), fullfile(outputPath, 'temp.gslib'));
        copyfile(fullfile(inputPath, 'mask.out'), fullfile(outputPath, 'mask.out'));
        copyfile(fullfile(inputPath, 'alldatacoor.gslib'), fullfile(outputPath, 'alldatacoor.gslib'));

        ncfilename = [datestr(targetDate, 'dd-mm-yyyy'), '_predModel_', num2str(dpt), '.nc'];
        copyfile(fileReal, fullfile(outputPath, ncfilename));
        delete(fullfile(inputPath, 'auxi.gslib'));
        delete(fullfile(inputPath, 'temp.gslib'));
        delete(fullfile(inputPath, 'mask.out'));

        giveCoordinateInformation_naza(0, 1, outputDays, imagesPath, [inputPath, filesep], [outputPath, filesep], inputDays, nx, ny, ncfilename);
        copyfile(fullfile(outputPath, ncfilename), fullfile(projectPath, ncfilename));
        save(fullfile(outputPath, 'finalworkspace.mat'));
        fprintf('Created %s\n', fullfile(projectPath, ncfilename));
    end
end
end

function ensure_dir(path_)
if ~exist(path_, 'dir')
    mkdir(path_);
end
end

function write_harddata(path_, data)
fid = fopen(path_, 'w');
fprintf(fid, '%s\n', 'seasurftemp');
fprintf(fid, '%s\n', '4');
fprintf(fid, '%s\n', 'x');
fprintf(fid, '%s\n', 'y');
fprintf(fid, '%s\n', 'z');
fprintf(fid, '%s\n', 'temp');
for f = 1:size(data,1)
    fprintf(fid, '%f\t', data(f,:));
    fprintf(fid, '\n');
end
fclose(fid);
end
"""


RUN_CONTROLLER_M = r"""function step10b_run_pilot_generation()
% STEP10B_RUN_PILOT_GENERATION Controller for safe MATLAB pilot generation.
cfg = step10b_pilot_config();
if ~exist(cfg.output_base, 'dir'); mkdir(cfg.output_base); end
if ~exist(cfg.logs_dir, 'dir'); mkdir(cfg.logs_dir); end
diary(fullfile(cfg.logs_dir, 'step10b_matlab_pilot_run.log'));
cleanup = onCleanup(@() diary('off'));

fprintf('Step10B MATLAB pilot generation\n');
fprintf('dry_run = %d\n', cfg.dry_run);
validate_step10b_config(cfg);
hres_table = write_selected_days_hres_step10b_pilot(cfg);
sim_table = run_selected_days_simulations_step10b_pilot(cfg);
save(fullfile(cfg.logs_dir, 'step10b_matlab_run_workspace.mat'), 'cfg', 'hres_table', 'sim_table');
fprintf('Step10B MATLAB pilot generation finished.\n');
end

function validate_step10b_config(cfg)
assert(isfolder(cfg.repo_root), 'Missing repo_root: %s', cfg.repo_root);
assert(isfolder(cfg.filipa_root), 'Missing filipa_root: %s', cfg.filipa_root);
assert(isfile(cfg.thetao_nc), 'Missing thetao_nc: %s', cfg.thetao_nc);
assert(isfile(cfg.dss_exe), 'Missing dss_exe: %s', cfg.dss_exe);
assert(isfile(cfg.bathy_reference_hres), 'Missing bathy_reference_hres: %s', cfg.bathy_reference_hres);
assert(numel(cfg.pilot_dates) == numel(cfg.pilot_classes), 'pilot_dates/classes size mismatch');
end
"""


README_M = """# Step10B MATLAB Pilot

This folder contains non-destructive MATLAB adaptations of Filipa's scripts.

Default behavior is `dry_run = true` in `step10b_pilot_config.m`.

Run in MATLAB:

```matlab
cd('SCRIPT_DIR_PLACEHOLDER')
cfg = step10b_pilot_config();
step10b_run_pilot_generation
```

After the dry-run is checked, edit only `cfg.dry_run = false` in
`step10b_pilot_config.m` and run the same controller again.
"""


def check_script_py() -> str:
    return r'''"""Check Step10B pilot predModels after MATLAB generation."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def latest_output() -> Path:
    candidates = sorted(RESULTS.glob("fossum_roi_x490_step10b_matlab_pilot_generation_*"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        raise FileNotFoundError("No Step10B MATLAB pilot output folder found.")
    return candidates[0]


def inspect_nc(path: Path) -> dict:
    import xarray as xr

    out = {"path": str(path), "exists": path.exists()}
    if not path.exists():
        return out
    ds = xr.open_dataset(path, decode_times=False)
    out["dims"] = dict(ds.sizes)
    out["variables"] = list(ds.variables)
    for name in ["TEMPpred", "STD", "LAT", "LON", "BATHY"]:
        out[f"has_{name}"] = name in ds.variables
    if "TEMPpred" in ds:
        arr = ds["TEMPpred"].values
        out["TEMPpred_shape"] = list(arr.shape)
        out["TEMPpred_all_nan"] = bool(np.isnan(arr).all())
        out["TEMPpred_valid_fraction"] = float(np.isfinite(arr).mean())
    if "STD" in ds:
        arr = ds["STD"].values
        out["STD_shape"] = list(arr.shape)
        out["STD_all_zero_or_nan"] = bool(np.nanmax(np.abs(arr)) == 0) if np.isfinite(arr).any() else True
        out["STD_valid_fraction"] = float(np.isfinite(arr).mean())
    ds.close()
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    out_dir = args.output.resolve() if args.output else latest_output().resolve()
    expected = pd.read_csv(out_dir / "step10b_expected_outputs.csv")
    pred = expected[expected["kind"].eq("predmodel")].copy()
    rows = []
    for _, row in pred.iterrows():
        info = inspect_nc(Path(row["expected_path"]))
        info.update({"date": row["date"], "class_id": row["class_id"], "depth": row["depth"]})
        rows.append(info)
    inv = pd.DataFrame(rows)
    inv.to_csv(out_dir / "step10b_pilot_predmodel_inventory.csv", index=False)
    checks = {
        "checked_at": datetime.now().isoformat(timespec="seconds"),
        "output_dir": str(out_dir),
        "expected_predmodels": int(len(pred)),
        "existing_predmodels": int(inv["exists"].sum()) if not inv.empty else 0,
        "pilot_dates_complete": bool(inv.groupby("date")["exists"].all().all()) if not inv.empty else False,
        "all_existing_have_TEMPpred": bool(inv[inv["exists"]]["has_TEMPpred"].all()) if "has_TEMPpred" in inv else False,
        "all_existing_have_STD": bool(inv[inv["exists"]]["has_STD"].all()) if "has_STD" in inv else False,
        "std_not_all_zero_for_existing": bool((~inv[inv["exists"]]["STD_all_zero_or_nan"]).all()) if "STD_all_zero_or_nan" in inv and inv["exists"].any() else False,
    }
    (out_dir / "step10b_pilot_predmodel_checks.json").write_text(json.dumps(checks, indent=2), encoding="utf-8")
    summary = [
        "# Step10B Pilot PredModel Check Summary",
        "",
        f"- Output: `{out_dir}`",
        f"- Expected predModels: {checks['expected_predmodels']}",
        f"- Existing predModels: {checks['existing_predmodels']}",
        f"- Pilot dates complete: {checks['pilot_dates_complete']}",
        f"- All existing have TEMPpred: {checks['all_existing_have_TEMPpred']}",
        f"- All existing have STD: {checks['all_existing_have_STD']}",
    ]
    (out_dir / "step10b_pilot_predmodel_check_summary.md").write_text("\n".join(summary), encoding="utf-8")
    print(json.dumps(checks, indent=2))


if __name__ == "__main__":
    main()
'''


def main() -> None:
    out_dir = RESULTS / f"fossum_roi_x490_step10b_matlab_pilot_generation_{now_tag()}"
    out_dir.mkdir(parents=True, exist_ok=False)
    SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    rows = pilot_rows()
    expected = expected_outputs(rows, out_dir)

    write_text(SCRIPT_DIR / "step10b_pilot_config.m", config_m(out_dir, rows))
    write_text(SCRIPT_DIR / "write_selected_days_hres_step10b_pilot.m", WRITE_HRES_M)
    write_text(SCRIPT_DIR / "run_selected_days_simulations_step10b_pilot.m", RUN_SIM_M)
    write_text(SCRIPT_DIR / "step10b_run_pilot_generation.m", RUN_CONTROLLER_M)
    write_text(SCRIPT_DIR / "README_step10b_pilot.md", README_M.replace("SCRIPT_DIR_PLACEHOLDER", matlab_path(SCRIPT_DIR)))
    write_text(ROOT / "scripts" / "10b_check_pilot_predmodels_generated.py", check_script_py())

    # Copy the config into the output folder for reproducibility.
    shutil.copy2(SCRIPT_DIR / "step10b_pilot_config.m", out_dir / "step10b_pilot_config.m")
    shutil.copy2(SCRIPT_DIR / "README_step10b_pilot.md", out_dir / "README_step10b_pilot.md")

    with (out_dir / "step10b_expected_outputs.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(expected[0].keys()))
        writer.writeheader()
        writer.writerows(expected)

    original_hashes = {
        "write14days.m": sha256(ORIG_WRITE),
        "runSimulations.m": sha256(ORIG_RUN),
    }
    audit = {
        "original_scripts": {
            "write14days.m": {
                "path": str(ORIG_WRITE),
                "sha256": original_hashes["write14days.m"],
                "inputs": ["thetao_20260427.nc", "external bathymetry deptho_N.nc in original script"],
                "outputs": ["CMEMSGrid NetCDF windows", "HRes NetCDF windows"],
                "hardcoded_paths": ["I:/dadosParaPedro_Fresnel", "F:/ProjectoInesOcean/Lucrezia/deptho_N.nc"],
                "hardcoded_dates": ["October loop: for i = 1:31", "uses end of thetao time series to select October days"],
                "main_variables": ["TEMPALL", "TIMEALL", "LAT", "LON", "DEPT", "BATHY", "TempHRes"],
                "toolboxes": ["MATLAB NetCDF functions", "Mapping Toolbox for projcrs/projfwd"],
            },
            "runSimulations.m": {
                "path": str(ORIG_RUN),
                "sha256": original_hashes["runSimulations.m"],
                "inputs": ["HRes NetCDF windows", "DSS.C.64.exe", "Functions/*.m"],
                "outputs": ["Daily_dpt_* folders", "Priori_Nazare_* folders", "predModel_N.nc with TEMPpred/STD"],
                "hardcoded_paths": ["I:/dadosParaPedro_Fresnel", "01.Data/October/HRes"],
                "hardcoded_dates": ["for dayDate = 1:2", "predDate = datetime('2024-10-30') + dayDate - 1"],
                "main_variables": ["predDate", "ProjectPath", "DataPath", "variogram", "nbrSim", "inputDays", "outputDays"],
                "toolboxes": ["MATLAB NetCDF functions", "Mapping Toolbox", "external DSS executable"],
            },
        },
        "adaptation": {
            "created_folder": str(SCRIPT_DIR),
            "dry_run_default": True,
            "pilot_dates_from_config": [r["date"] for r in rows],
            "target_dates_not_hardcoded_in_main_body": True,
            "new_scripts_use_local_paths": True,
            "new_scripts_do_not_modify_originals": True,
            "bathy_adaptation": "Uses existing October HRes BATHY as a grid-consistent reference for new HRes files.",
            "required_hres_end_dates": [d.strftime("%Y-%m-%d") for d in required_hres_dates(rows)],
        },
    }
    write_json(out_dir / "step10b_matlab_original_scripts_audit.json", audit)

    audit_md = [
        "# Step10B MATLAB Original Scripts Audit",
        "",
        "## Original Scripts",
        f"- `{ORIG_WRITE}`",
        f"- `{ORIG_RUN}`",
        "",
        "## Hardcoded Paths/Dates",
        "- `write14days.m`: local source/output paths and October 31-day loop.",
        "- `runSimulations.m`: local source/output paths, October HRes folder, and two hardcoded prediction days.",
        "",
        "## Adaptation",
        "- New MATLAB scripts are written under `scripts/matlab_step10b_pilot`.",
        "- Original scripts were not edited.",
        "- Pilot dates live in `step10b_pilot_config.m`.",
        "- `dry_run = true` by default.",
        "- New scripts use local repo paths and output only inside the Step10B output folder.",
        "- HRes windows needed for the pilot are target date minus 1 day and target date plus 1 day, matching the original simulation and validation lookup pattern.",
    ]
    write_text(out_dir / "step10b_matlab_original_scripts_audit.md", "\n".join(audit_md))

    inputs = [
        {"input": "thetao_20260427.nc", "path": str(THETAO_NC), "exists": THETAO_NC.exists(), "required_for": "HRes generation"},
        {"input": "DSS.C.64.exe", "path": str(DSS_EXE), "exists": DSS_EXE.exists(), "required_for": "DSS simulation"},
        {"input": "bathy_reference_hres", "path": str(BATHY_REFERENCE_HRES), "exists": BATHY_REFERENCE_HRES.exists(), "required_for": "HRes BATHY grid"},
        {"input": "pilot_dates_csv", "path": str(PILOT_CSV), "exists": PILOT_CSV.exists(), "required_for": "pilot selection"},
        {"input": "Filipa Functions", "path": str(FILIPA_ROOT / "00.Code" / "Functions"), "exists": (FILIPA_ROOT / "00.Code" / "Functions").exists(), "required_for": "MATLAB simulation helpers"},
    ]
    pd.DataFrame(inputs).to_csv(out_dir / "step10b_required_inputs_check.csv", index=False)

    matlab_on_path = shutil.which("matlab") is not None
    missing = []
    if not matlab_on_path:
        missing.append({"dependency": "MATLAB on PATH", "status": "missing_from_shell_path", "impact": "Use MATLAB GUI/Command Window manually."})
    missing.append({"dependency": "MATLAB Mapping Toolbox", "status": "unknown_until_matlab_run", "impact": "Required for projcrs/projfwd."})
    pd.DataFrame(missing).to_csv(out_dir / "step10b_missing_dependencies.csv", index=False)

    plan = [
        "# Step10B MATLAB Pilot Generation Plan",
        "",
        "1. Run MATLAB dry-run with the generated config.",
        "2. Confirm planned HRes and predModel paths.",
        "3. Set `cfg.dry_run = false` in `step10b_pilot_config.m`.",
        "4. Generate only the 4 pilot dates.",
        "5. Run `python scripts/10b_check_pilot_predmodels_generated.py --output <output_folder>`.",
        "6. Only after checks pass, create Step10C ROI x490 extraction.",
    ]
    write_text(out_dir / "step10b_generation_plan.md", "\n".join(plan))

    instructions = [
        "# Step10B Manual MATLAB Execution Instructions",
        "",
        "MATLAB is not available on the shell PATH here, so run this in MATLAB GUI/Command Window.",
        "",
        "```matlab",
        f"cd('{matlab_path(SCRIPT_DIR)}')",
        "cfg = step10b_pilot_config();",
        "cfg.dry_run",
        "step10b_run_pilot_generation",
        "```",
        "",
        "After dry-run succeeds, edit `step10b_pilot_config.m` and change:",
        "",
        "```matlab",
        "cfg.dry_run = false;",
        "```",
        "",
        "Then run again:",
        "",
        "```matlab",
        "cd('" + matlab_path(SCRIPT_DIR) + "')",
        "step10b_run_pilot_generation",
        "```",
        "",
        f"Expected output folder: `{out_dir}`",
        "",
        "After MATLAB finishes, validate predModels from PowerShell:",
        "",
        "```powershell",
        f"python scripts\\10b_check_pilot_predmodels_generated.py --output \"{out_dir}\"",
        "```",
    ]
    write_text(out_dir / "step10b_manual_matlab_execution_instructions.md", "\n".join(instructions))

    report = [
        "# Step10B MATLAB Pilot Preparation Report",
        "",
        "Prepared non-destructive MATLAB adaptations for the 4 C01/C06 pilot dates.",
        "",
        f"- Output folder: `{out_dir}`",
        f"- MATLAB script folder: `{SCRIPT_DIR}`",
        f"- MATLAB on PATH: {matlab_on_path}",
        f"- DSS executable exists: {DSS_EXE.exists()}",
        f"- thetao source exists: {THETAO_NC.exists()}",
        "- No simulation was executed by this preparation step.",
        "- No TEMPpred/STD pilot arrays were invented.",
        "",
        "Verdict: READY_FOR_MANUAL_MATLAB_DRY_RUN",
    ]
    write_text(out_dir / "step10b_report.md", "\n".join(report))
    write_text(out_dir / "step10b_summary.md", "\n".join(report[:12]))

    checks = {
        "original_write_hash_before_after_same": sha256(ORIG_WRITE) == original_hashes["write14days.m"],
        "original_run_hash_before_after_same": sha256(ORIG_RUN) == original_hashes["runSimulations.m"],
        "new_scripts_contain_I_drive": any("I:\\" in p.read_text(encoding="utf-8", errors="ignore") for p in SCRIPT_DIR.glob("*.m")),
        "pilot_dates_in_config": True,
        "dry_run_default": True,
        "dss_exists": DSS_EXE.exists(),
        "thetao_exists": THETAO_NC.exists(),
        "matlab_on_path": matlab_on_path,
        "expected_predmodels_exist_before_generation": any(row["exists_now"] for row in expected if row["kind"] == "predmodel"),
        "verdict": "READY_FOR_MANUAL_MATLAB_DRY_RUN",
    }
    write_json(out_dir / "step10b_preparation_checks.json", checks)

    print(f"Step10B MATLAB pilot preparation complete: {out_dir}")
    print(f"MATLAB scripts: {SCRIPT_DIR}")
    print(f"Verdict: {checks['verdict']}")


if __name__ == "__main__":
    main()
